agent.sources = source1
agent.sinks = sink1
agent.channels = channel1

agent.sources.source1.type = spooldir
agent.sources.source1.spoolDir = /home/bigdata/flume_spool
agent.sources.source1.fileHeader = true

agent.channels.channel1.type = memory
agent.channels.channel1.capacity = 1000
agent.channels.channel1.transactionCapacity = 100

agent.sinks.sink1.type = hdfs
agent.sinks.sink1.hdfs.path = hdfs://localhost:9000/hotel_project/input
agent.sinks.sink1.hdfs.fileType = DataStream
agent.sinks.sink1.hdfs.writeFormat = Text
agent.sinks.sink1.hdfs.batchSize = 100
agent.sinks.sink1.hdfs.rollCount = 0
agent.sinks.sink1.hdfs.rollSize = 0
agent.sinks.sink1.hdfs.rollInterval = 0

agent.sources.source1.channels = channel1
agent.sinks.sink1.channel = channel1

